src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $TypeId;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="time")
     */
    private $Start;

    /**
     * @ORM\Column(type="time")
     */
    private $End;

    /**
     * @ORM\Column(type="dateinterval")
     */
    private $Duration;

    /**
     * @ORM\Column(type="boolean")
     */
    private $IsPast;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeId(): ?int
    {
        return $this->TypeId;
    }

    public function setTypeId(int $TypeId): self
    {
        $this->TypeId = $TypeId;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->Start;
    }

    public function setStart(\DateTimeInterface $Start): self
    {
        $this->Start = $Start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->End;
    }

    public function setEnd(\DateTimeInterface $End): self
    {
        $this->End = $End;

        return $this;
    }

    public function getDuration(): ?\DateInterval
    {
        return $this->Duration;
    }

    public function setDuration(\DateInterval $Duration): self
    {
        $this->Duration = $Duration;

        return $this;
    }

    public function getIsPast(): ?bool
    {
        return $this->IsPast;
    }

    public function setIsPast(bool $IsPast): self
    {
        $this->IsPast = $IsPast;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message= "L'adresse mail ne peut pas etre vide")
     */
    private $email;

     /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ProfilePic;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Avatar;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\UserCategory", inversedBy="Users")
     */
    private $Category;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\UsersMatter", mappedBy="User")
     */
    private $usersMatters;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Address", mappedBy="User", cascade={"persist", "remove"})
     */
    private $address;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Availability", mappedBy="User")
     */
    private $availabilities;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Lesson", mappedBy="Teacher")
     */
    private $lessons;

    public function __construct()
    {
        $this->usersMatters = new ArrayCollection();
        $this->availabilities = new ArrayCollection();
        $this->lessons = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }


    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getProfilePic(): ?string
    {
        return $this->ProfilePic;
    }

    public function setProfilePic(?string $ProfilePic): self
    {
        $this->ProfilePic = $ProfilePic;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $Address): self
    {
        $this->address = $Address;

        return $this;
    }



    public function getAvatar(): ?string
    {
        return $this->Avatar;
    }

    public function setAvatar(?string $Avatar): self
    {
        $this->Avatar = $Avatar;

        return $this;
    }

    public function getCategory(): ?UserCategory
    {
        return $this->Category;
    }

    public function setCategory(?UserCategory $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection|UsersMatter[]
     */
    public function getUsersMatters(): Collection
    {
        return $this->usersMatters;
    }

    public function addUsersMatter(UsersMatter $usersMatter): self
    {
        if (!$this->usersMatters->contains($usersMatter)) {
            $this->usersMatters[] = $usersMatter;
            $usersMatter->setUser($this);
        }

        return $this;
    }

    public function removeUsersMatter(UsersMatter $usersMatter): self
    {
        if ($this->usersMatters->contains($usersMatter)) {
            $this->usersMatters->removeElement($usersMatter);
            // set the owning side to null (unless already changed)
            if ($usersMatter->getUser() === $this) {
                $usersMatter->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Availability[]
     */
    public function getAvailabilities(): Collection
    {
        return $this->availabilities;
    }

    public function addAvailability(Availability $availability): self
    {
        if (!$this->availabilities->contains($availability)) {
            $this->availabilities[] = $availability;
            $availability->setUser($this);
        }

        return $this;
    }

    public function removeAvailability(Availability $availability): self
    {
        if ($this->availabilities->contains($availability)) {
            $this->availabilities->removeElement($availability);
            // set the owning side to null (unless already changed)
            if ($availability->getUser() === $this) {
                $availability->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->setTeacher($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->contains($lesson)) {
            $this->lessons->removeElement($lesson);
            // set the owning side to null (unless already changed)
            if ($lesson->getTeacher() === $this) {
                $lesson->setTeacher(null);
            }
        }

        return $this;
    }

    

}

src/Controller/AgendaController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Availability;
use App\Entity\TimeSlot;
use App\Entity\User;
use App\Repository\AvailabilityRepository;
use App\Repository\TimeSlotRepository;
use DateTime;
use App\Form\TimeSlotType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Validator\ValidatorInterface;


class AgendaController extends AbstractController
{
    /**
     *@var AvailabilityRepository
     */
    private $repository;
    
    public function __construct(AvailabilityRepository $AvailabilityRepository, TimeSlotRepository $TimeSlotRepository)
    {
        $this->AvRepository=$AvailabilityRepository;
        $this->TSRepository=$TimeSlotRepository;
    }
    
    /**
     * @Route("/agenda", name="agenda")
     */
    public function index(Request $request,ValidatorInterface $validator)
    {
        $user = $this->getUser();
        $availability=new Availability();
        $TimeSlot=new TimeSlot();
        $availabilities=$this->AvRepository->findByUser($user);
        $TimeSlots=$this->TSRepository->findAll();
        dump($TimeSlots);
        
        
        $form=$this->createForm(TimeSlotType::class, $TimeSlot);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){ 
            //TimeSlotType data is inserted into $TimeSlot entity
            $Date=new DateTime($form->get('Date')->getData());
            $start=new DateTime('1970-01-01 '.$form->get('start')->getData());
            $end = new DateTime('1970-01-01 '.$form->get('end')->getData());
            $TimeSlot->setDate($Date);
            $TimeSlot->setStart($start);
            $TimeSlot->setEnd($end);
            $TimeSlot->setDuration();
            $TimeSlot->setIsPast();
            
            $availability->setTimeSlot($TimeSlot);
            $availability->setUser($user);
            $condition = true;
            dump ($condition);   
            if ($condition==true)
            {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($availability,$TimeSlot);
                $entityManager->flush(); 
            }
            else
            {
                dump ('Les dispos se chevauchent');
            }
            
           
        }
        $availabilities=$this->AvRepository->findByUser($user);
        $TimeSlots=$this->TSRepository->findAll();
       
        $lessons=$user->getLessons();
        $events = array();
        foreach ($availabilities as $av)
        {
            $event=array("id"=>$av->getTimeSlot()->getId(),'start'=>$av->getTimeSlot()->getDate()->format('Y-m-d').'T'.$av->getTimeSlot()->getStart()->format('H:i:s'),'end'=>$av->getTimeSlot()->getDate()->format('Y-m-d').'T'.$av->getTimeSlot()->getEnd()->format('H:i:s'),'title'=>'availability')
                         ;
            array_push($events, $event);            
        }
        //$events=json_encode($events);
        dump($availabilities);
        dump($user);
        //dump($lessons);
        //dump($TimeSlot);
        //dump($availability);
        dump($events);
        return $this->render('agenda/index.html.twig', [
            'controller_name' => 'AgendaController',
            'user' => $user,
            'lessons'=> $lessons,
            'availabilities' => $availabilities,
            'form'=>$form->createView(),
            'events'=>$events,
        ]);
    }
}

templates/agenda/content.html.twig
{%extends 'sections/main-content.html.twig'%}

{%block content%}
	<div class="example-wrapper">
		<h1>Hello {{ user.firstName }}</h1>
		<p> Bienvenue sur ton Agenda</p>
		<div class="panel col-md-8">
			<div class="panel-body">
				<div id="calendar" class="has-toolbar"></div>
         </div>
      </div>
		<div class="panel col-md-4">
			<div class='panel-body'>
				<h3>Ajouter des disponibilités</h3>
				{{form_start(form)}}
					{{form_row(form.Date)}}
					{{form_row(form.start)}}
					{{form_row(form.end)}}					
					<input type='submit'>
			  {{form_end(form)}}
				 
			</div>
		</div>
		
            <ul>
						 
            </ul>
        </div>
{%endblock%}

templates/agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AgendaController!{% endblock %}



{% block body %}
{{include ('sections/header/'~user.Category.category~'.html.twig')}}
{{include ('sections/sidebar/sidebar.html.twig')}}
{{include ('agenda/content.html.twig')}}

{% endblock %}

{%block stylesheets%}
	<link href='/assets/lib/Full-calendar/packages/core/main.css' rel='stylesheet' />
	<link href='/assets/lib/Full-calendar/packages/daygrid/main.css' rel='stylesheet' />
	<link href='/assets/lib/Full-calendar/packages/timegrid/main.css' rel='stylesheet' />
    <link href="/assets/lib/datepicker/css/datepicker.css" rel="stylesheet">
{%endblock%}

{%block javascripts%}
	 <!--scripts for this page-->
  <!--  Full calendar:-->
  <script src='/assets/lib/Full-calendar/packages/core/main.js'></script>
  <script src='/assets/lib/Full-calendar/packages/interaction/main.js'></script>
  <script src='/assets/lib/Full-calendar/packages/daygrid/main.js'></script>
  <script src='/assets/lib/Full-calendar/packages/timegrid/main.js'></script>
<!-- Date and Time Pickers-->
 <script src="lib/jquery-ui-1.9.2.custom.min.js"></script>
  <script type="text/javascript" src="lib/bootstrap-fileupload/bootstrap-fileupload.js"></script>
  <script type="text/javascript" src="lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
  <script type="text/javascript" src="lib/bootstrap-daterangepicker/date.js"></script>
  <script type="text/javascript" src="lib/bootstrap-daterangepicker/daterangepicker.js"></script>
  <script type="text/javascript" src="lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
  <script type="text/javascript" src="lib/bootstrap-daterangepicker/moment.min.js"></script>
  <script type="text/javascript" src="lib/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
  <script src="lib/advanced-form-components.js"></script>
  <!--Script pour le format de date-->
  <script src=dateHtml.js ></script>
  <script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'interaction', 'dayGrid', 'timeGrid' ],
      defaultView: 'dayGridMonth',
      themeSystem: 'bootstrap',
      showNonCurrentDates: true,
      fixedWeekCount: false,
      header:{
        left:'today prev,next',
        center:'title',
        right:'dayGridMonth,timeGridWeek,timeGridDay'
        },
      
      allDaySlot: false,
      slotDuration: "00:30:00",
      minTime: "07:00:00",
      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: /*{start: '2020-06-06T08:00:00',end: '2020-06-06T11:00:00' , title: 'exemple'},
               {start: '2020-06-08T08:00:00',end: '2020-06-08T11:00:00' , title: 'exemple2'}*/
      [{"id":2,"start":"2020-06-08T11:00:00","end":"2020-06-08T16:00:00","title":"availability"},
        {%for event in events%}
            {"id":{{event.id}},"start":"{{event.start}}","end":"{{event.end}}","title":"availability"},
        {%endfor %}
       ],
    });

    calendar.render();
  });

</script>
{%endblock%}